author: 'Exakat SAS'
branding:
    icon: 'check-circle'
    color: 'orange'
inputs:
  ignore_dirs:
    description: 'Dirs and files to ignore in the repository. Comma separated list of path. i.e. "path/to/files,path/to/others/files".'
    required: false
    default: ''
  include_dirs:
    description: 'Dirs and files to include in the repository. Comma separated list of path. i.e. "path/to/files,path/to/others/files".'
    required: false
    default: ''
  ignore_rules:
    description: 'Exakat rules to skip in this audit. Comma separated list of exakat identifiers "Short Name" : i.e. "Structures/AddZero,Structures/StrposCompare".'
    required: false
    default: ''
  project_reports:
    description: 'The format of the report for the audit. It may be Perfile (default) or Sarif (for Github consumption). Multiple reports may be provided as a comma separated list : "Perfile,Sarif,Diplomat"'
    required: false
    default: 'Perfile'
  project_rulesets:
    description: 'Name of the rulesets to be used with the action. It may be CI-checks (default), one of Exakat default rulesets (see docs), or a custom ruleset configured with .exakat.yaml. Multiple rulesets may be provided as a comma separated list : "CI-checks,Security,MyRuleset"'
    required: false
    default: 'CI-checks'
  exit_on_issue:
    description: 'Exit(1) when one or more issues are found. Default to true. Set this to empty string, when producing report for future usage.'
    required: false
    default: 'true'
description: 'Scan with the Exakat GitHub Action your PHP code to detect tricky issue, prevent vulnerabilities and control the quality'
name: 'Exakat'
runs:
    using: 'docker'
    image: 'docker://exakat/exakat-ga'